### ISSUE TITLE
Question: How is this repository supposed to be used?

### ISSUE THREAD

**Issue by galenseilis** [jessestewart1/nrn-rrn#162]
I am interested in downloading national road network data. Googling that topic led me to this repository, but it is unclear to me from the [docs](https://nrn-rrn-docs.readthedocs.io/en/latest/) on whether it achieves that purpose. 

I followed the repo instructions of cloning to a local system, but unlike the repo instructions I am not sure what needs to be run or decompressed. 

What is this repository for? If it is for accessing national road network data, then documenting an example of its usage would be beneficial.

**Comment by galenseilis** [comment]
To access the data I am interested in, I can just use [this FTP site](https://ftp.maps.canada.ca/pub/nrcan_rncan/vector/geobase_nrn_rrn/). But I am still curious about what this repository is for.

**Comment by jessestewart1** [comment]
Recognizing this is nearly a year old - apologies, outside users have never opened issues on the repo until this one. The repository is made public just for transparency of the NRN pipeline as it contains no confidential information. This repo may one day become private if needed. There is no real reason for anybody to actually use it outside of those responsible for producing the NRN products.

Data is publicly available here: https://open.canada.ca/data/en/dataset/3d282116-e556-400c-9306-ca1a3cada77f
